- README.md
Closes: https://github.com/Shopify/maintenance_tasks/issues/275
Documents the various statuses a Task (Run) can be in, along with screenshots, in the README.
> Document Task statuses in README

- db/migrate/20201211151756_create_maintenance_tasks_runs.rb
Closes: https://github.com/Shopify/maintenance_tasks/issues/238
As we prepare to open-source, we should drop the `force: true` flag from the `maintenance_tasks_runs` table so that we no longer drop the table before creating it. Any changes to our data models will need to be applied as new migrations moving forward.
> Remove force: true flag on runs table

- README.md
- shipit.yml
That should let shipit deploy to rubygems by default.
> Push to rubygems

- app/models/maintenance_tasks/runner.rb
- lib/maintenance_tasks.rb
- test/lib/maintenance_tasks_test.rb
- test/models/maintenance_tasks/runner_test.rb
Similar to what was done in #255 for `task_module`, this change returns a String for the job class name, which can be constantized where necessary.
> Return the Task Job as a string in the config

- README.md
- lib/maintenance_tasks.rb
- lib/maintenance_tasks/integrations/bugsnag_handler.rb
- test/lib/maintenance_tasks_test.rb
This reverts PR #248. I don't think we should make assumptions about the usage of Bugsnag. As long as we make integrating Bugsnag possible, and document it in the README, it should suffice.
> Revert "Merge pull request #248 from Shopify/bugsnag-integration"

- app/helpers/maintenance_tasks/application_helper.rb
With #294, and assuming our users use either 6.0 or 6.1.1 but not 6.1.0, we can remove this patch that was merged upstream in https://github.com/rails/rails/pull/40841 (included in 6.1.1 with https://github.com/rails/rails/commit/80077d3675b9baceb0fee2a9bef8fcce9cf7080c)
I'm not sure it warrants adding that to the gemspec given our stance that dependencies should always be up-to-date.
> Remove stylesheet_link_tag patch

- app/jobs/maintenance_tasks/task_job.rb
- app/validators/maintenance_tasks/run_status_validator.rb
- test/jobs/maintenance_tasks/task_job_test.rb
- test/validators/maintenance_tasks/run_status_validator_test.rb
If a Task is enqueued and is then deleted before being performed, or if a Task is interrupted and deleted, it results in a crash.
To repro:
```sh-session
$ bundle add sidekiq
$ $EDITOR test/dummy/config/application.rb
```
Start a server, visit http://localhost:3000/maintenance_tasks/tasks/Maintenance::UpdatePostsTask, start a run then:
```
$ rm test/dummy/app/tasks/maintenance/update_posts_task.rb
$ (cd test/dummy; bundle exec sidekiq)
```
This is fixed by the first commit.
```
$ git checkout task-deleted-during-run^
$ (cd test/dummy; bundle exec sidekiq)
```
```sh-session
$ git restore -- test/dummy/app/tasks/maintenance/update_posts_task.rb
$ (cd test/dummy; bundle exec sidekiq)
$ rm test/dummy/app/tasks/maintenance/update_posts_task.rb
$ (cd test/dummy; bundle exec sidekiq)
```
This is …
> Handle error handling for deleted tasks

- README.md
- app/controllers/maintenance_tasks/tasks_controller.rb
- app/models/maintenance_tasks/runner.rb
- app/tasks/maintenance_tasks/task.rb
- lib/generators/maintenance_tasks/templates/task_spec.rb.tt
- lib/generators/maintenance_tasks/templates/task_test.rb.tt
- lib/maintenance_tasks/cli.rb
- test/lib/maintenance_tasks/cli_test.rb
- test/models/maintenance_tasks/runner_test.rb
- test/tasks/maintenance_tasks/task_test.rb
This PR simplifies the API by removing the need to call new for public APIs:
```diff
- MaintenanceTasks::Runner.new.run(name: 'Maintenance::UpdatePostsTask')
+ MaintenanceTasks::Runner.run(name: 'Maintenance::UpdatePostsTask')
```
Mostly for tests, but I could see the `process` one being used:
```diff
- MaintenanceTasks::Task.new.process(item)
+ MaintenanceTasks::Task.process(item)
- MaintenanceTasks::Task.new.collection
+ MaintenanceTasks::Task.collection
- MaintenanceTasks::Task.new.count
+ MaintenanceTasks::Task.count
```
> Remove the need to call new for public APIs

- test/dummy/db/migrate/20210112141723_create_active_storage_tables.active_storage.rb
- test/dummy/db/schema.rb
Closes: https://github.com/Shopify/maintenance_tasks/issues/200
CSV functionality has been requested by a number of users at this point, so I think it makes sense to start building out this feature.
This PR sets up ActiveStorage in the dummy app by adding the necessary tables (from https://edgeguides.rubyonrails.org/active_storage_overview.html#setup, these were generated by doing `cd test/dummy; rails active_storage:install; rails db:migrate`).
We've settled on using the ActiveStorage library Rails provides because it seems reasonable for an uploaded CSV to be attached to a `Run` record, and ActiveStorage makes it simple for users to set up their apps with a cloud storage solution to store their uploaded CSVs.
> Add ActiveStorage to the dummy app

- app/tasks/maintenance_tasks/task.rb
- test/tasks/maintenance_tasks/task_test.rb
This code was introduced [in this PR](https://github.com/Shopify/maintenance_tasks/pull/77) in an attempt to decouple Tasks from Jobs. In introducing the Task class, we had to couple it with JobIteration's enumerator builder so that we wouldn't change the existing API too much (we were trying to minimize changes in that single PR IIRC).
https://github.com/Shopify/maintenance_tasks/pull/93 was opened as a follow up to decouple Task from JobIteration's enumerator builder, but this convenience method was left over.
There's no need for it now that Task's API is decoupled entirely from JobIteration.
> Remove dead code in Task

- app/models/maintenance_tasks/run.rb
- app/models/maintenance_tasks/runner.rb
- test/fixtures/files/sample.csv
- test/models/maintenance_tasks/runner_test.rb
Smallish PR, as ActiveStorage handles all of the complexity associated with attaching an uploaded file to an ActiveRecord.
This PR attaches a `csv_file` to our Run model using the `has_one_attached` macro (this will always be a 1:1 relationship).
The `Runner` class is now responsible for attaching an incoming `csv_file` to newly created runs in its `#run` method. It will be up to the `TasksController` / CLI to pass the CSV from the UI or command line to the runner.
> Attach CSVs to runs

- README.md
Closes: https://github.com/Shopify/maintenance_tasks/issues/304
We should document in the installation step of the README that the queue adapter for ActiveJob needs to be configured to a persistent backend (ie. not the default async backend) in order for tasks continue running through infra changes / code deploys / etc...
> Add note about ActiveJob to README

- README.md
- app/tasks/maintenance_tasks/csv_task.rb
- app/tasks/maintenance_tasks/task.rb
- lib/generators/maintenance_tasks/templates/csv_task.rb.tt
- test/dummy/app/tasks/maintenance/import_posts_task.rb
- test/lib/generators/maintenance_tasks/task_generator_test.rb
Change the implementation of `CsvTask` to be a class from which application Tasks can inherit from, instead of a mixin.
It was unclear to me whether we're okay keeping the use of `respond_to?(csv_content=)` in `TaskJob` when setting `csv_content` on a Task:
https://github.com/Shopify/maintenance_tasks/blob/d5835468ea104dbe7c58fe4932c207229eaacb35/app/jobs/maintenance_tasks/task_job.rb#L59-L62
Or whether we wanted to introduce a class-level method like `csv_task?` instead. Let me know!
> Use superclass for CSV method

- app/controllers/maintenance_tasks/tasks_controller.rb
- app/models/maintenance_tasks/task_data.rb
- app/views/maintenance_tasks/tasks/_upload_csv.html.erb
- app/views/maintenance_tasks/tasks/actions/_cancelled.html.erb
- app/views/maintenance_tasks/tasks/actions/_cancelling.html.erb
- app/views/maintenance_tasks/tasks/actions/_enqueued.html.erb
- app/views/maintenance_tasks/tasks/actions/_errored.html.erb
- app/views/maintenance_tasks/tasks/actions/_interrupted.html.erb
- app/views/maintenance_tasks/tasks/actions/_new.html.erb
- app/views/maintenance_tasks/tasks/actions/_paused.html.erb
- app/views/maintenance_tasks/tasks/actions/_pausing.html.erb
- app/views/maintenance_tasks/tasks/actions/_running.html.erb
- app/views/maintenance_tasks/tasks/actions/_succeeded.html.erb
- app/views/maintenance_tasks/tasks/show.html.erb
- test/models/maintenance_tasks/task_data_test.rb
- test/system/maintenance_tasks/runs_test.rb
Closes: https://github.com/Shopify/maintenance_tasks/issues/202
Allows files to be uploaded for CSV Tasks in the UI. I've modified any of the action partials that allow a Task to be run to use the [form_helper](https://api.rubyonrails.org/v6.1.1/classes/ActionView/Helpers/FormHelper.html#method-i-form_with) so that we can allow files to be submitted via a file input upload tag. The views call a new method `TaskData#csv_task?` to determine whether to render the file upload element.
I've also modified the TasksController show action to only set `@refresh` if there is an active run - this avoids unnecessarily refreshing when nothing is happening, which is particularly important for CSV Tasks, since the form might get refreshed before it is submitted with the current refresh behaviour (wiping …
> Allow uploading CSVs to CSV supporting Tasks through the UI

- app/tasks/maintenance_tasks/task.rb
- test/jobs/maintenance_tasks/task_job_test.rb
- test/tasks/maintenance_tasks/task_test.rb
Before this commit, we raised a `NotImplementedError` exception, which doesn't inherit from `StandardError` so is not caught by our `rescue_from`.
Even if we try to change our rescue_from to rescue from `NotImplementedError`, `ActiveJob::Execution#perform_now` doesn't rescue `Exception` like `ActionController::Rescue#process` does, so it doesn't catch the exception.
https://github.com/rails/rails/blob/v6.1.1/activejob/lib/active_job/execution.rb#L50
https://github.com/rails/rails/blob/v6.1.1/actionpack/lib/action_controller/metal/rescue.rb#L23
Close #301
> Set Task as errored if the Task doesn't define collection or process

- README.md
- app/models/maintenance_tasks/csv_collection.rb
- app/models/maintenance_tasks/task_data.rb
- app/tasks/maintenance_tasks/task.rb
- lib/generators/maintenance_tasks/templates/csv_task.rb.tt
- test/dummy/app/tasks/maintenance/import_posts_task.rb
- test/lib/generators/maintenance_tasks/task_generator_test.rb
- test/lib/maintenance_tasks_test.rb
In #302 we went with a new subclass, which we refactored to a module to be included in a Task.
We got feedback in https://github.com/Shopify/maintenance_tasks/pull/302#discussion_r562911483 but we can't really change the behavior only based on data from the Run (a CSV file being present), since we need to know something about the class to show the input which results in a CSV file being updated. The class itself needs to somehow declare that it supports CSV.
Rafael pointed out that we shouldn't use `include` as an API for changing behavior to the classes, we discussed that on Slack but we missed the mark with #313 when we went instead with a superclass, as explained in https://github.com/Shopify/maintenance_tasks/pull/310#issuecomment-768529654.
So instead this PR uses a class method on …
> Use a class method to declare a CSV task

- app/controllers/maintenance_tasks/runs_controller.rb
- app/helpers/maintenance_tasks/task_helper.rb
- app/models/maintenance_tasks/task_data.rb
- app/views/maintenance_tasks/runs/_info.html.erb
- test/application_system_test_case.rb
- test/helpers/maintenance_tasks/task_helper_test.rb
- test/system/maintenance_tasks/runs_test.rb
This PR leverages [ Active Storage's download link helper](https://guides.rubyonrails.org/active_storage_overview.html#linking-to-files) to provide download links for CSV attachments associated with previous runs for CSV Tasks. Note that we have to use `Rails.application.routes.url_helpers.rails_blob_path` instead of `rails_blob_path` because the download URL is associated with the host app, not the engine (and additionally, we don't specify Active Storage as a dependency of the engine, so this helper isn't even available to us).
Since we're using `run.csv_file.attached?` to check whether to show the download link, I've added preloading for the CSV file attachments when we generate the `ActiveRecord::Relation` for Runs, as @etiennebarrie suggested. (And we can use …
> Allow CSV files for previous runs to be downloaded via the UI

- README.md
Users at Shopify encounter a warning during `bundle install` due to the fact that the gem is registered at rubygems.org and in our internal package system:
```bash
Warning: the gem 'maintenance_tasks' was found in multiple sources.
Installed from: https://rubygems.org/
Also found in:
* https://packages.shopify.io/shopify/gems/
You should add a source requirement to restrict this gem to your preferred source.
For example:
gem 'maintenance_tasks', :source => 'https://rubygems.org/'
Then uninstall the gem 'maintenance_tasks' (or delete all bundled gems) and then install again.
```
IMHO we should tell users to source the gem from the public source in the README to prevent this issue.
> Add rubygems source to Gemfile line in README

- README.md
- app/jobs/maintenance_tasks/task_job.rb
- lib/maintenance_tasks.rb
- test/jobs/maintenance_tasks/task_job_test.rb
- test/lib/maintenance_tasks_test.rb
Closes: https://github.com/Shopify/maintenance_tasks/issues/309
This PR changes the call to the defined error handler to pass along an additional `task_context` argument. This arg is a hash containing some additional information about the Task and the corresponding run.
An example of how users can leverage this info has been added to the `README`: if they integrate with Bugsnag, the simplest thing to do would just be to add a tab containing the details of the Task's context when notifying.
We might want to think a bit more about what information it makes sense to expose. Assuming that most users are using Sidekiq for their queuing backend, a lot of the information pertaining to the job is exposed through the `job_context` (as shown in the original issue) - `job_id`, `cursor`, `job_class`, …
> Supply additional task info as argument when calling error handler

- app/models/maintenance_tasks/runner.rb
- test/models/maintenance_tasks/runner_test.rb
#296 removed `Runner.new` to instead support `Runner.run` directly, but this creates an incompatibility for existing users who were using that API. This brings it back and uses `ActiveSupport::Deprecation.warn` to indicate that users should start using `Runner.run` directly.
> Deprecate Runner.new.run in favour of Runner.run

- README.md
- app/models/maintenance_tasks/run.rb
- lib/maintenance_tasks/cli.rb
- test/helpers/maintenance_tasks/task_helper_test.rb
- test/jobs/maintenance_tasks/task_job_test.rb
- test/lib/maintenance_tasks/cli_test.rb
- test/models/maintenance_tasks/run_test.rb
- test/models/maintenance_tasks/runner_test.rb
This should be the last missing piece for CSV functionality in the gem. This PR allows a file to be passed via a `--csv` option on the CLI in order to run CSV processing Tasks from the command line.
- https://github.com/Shopify/maintenance_tasks/commit/039e3e9889e348ea5dd2671cb860a7848160730d adds a `--csv` option to the CLI. If a file is supplied, we build an attachable (see https://edgeguides.rubyonrails.org/active_storage_overview.html#attaching-file-io-objects) to send to `Runner.run`. The CLI will surface the error if the file doesn't exist / isn't openable / etc.
- https://github.com/Shopify/maintenance_tasks/commit/ab1ee8c943867b6f7265de4efb43fe9e07c14c97 modifies `Runner.run` to verify that the Task processes CSVs before attaching the CSV (since a user can now pass a CSV for a …
> Enqueue CSVs from the CLI

- app/helpers/maintenance_tasks/tasks_helper.rb
- test/dummy/config/application.rb
- test/helpers/maintenance_tasks/tasks_helper_test.rb
Problem:
When `config.action_controller.include_all_helpers = false`, helpers are
not available by default which leads to `undefined method 'status_tag'`.
Solution:
By following the rails naming convention, necessary helpers are
automatically included by rails.
> Follow the rails naming convention

- app/views/maintenance_tasks/runs/_info.html.erb
- app/views/maintenance_tasks/runs/_run.html.erb
Duplicated timestamps are showing up for previous runs on the show page, since: https://github.com/Shopify/maintenance_tasks/pull/288.
We need to bring back conditionally showing `run.status` in the `_info` partial based on the value of `with_status`, and then have `_run` render the `_info` partial without duplicating the heading.
> Fix duplicated timestamps for previous runs on show page

- db/migrate/20210225152418_remove_index_on_task_name.rb
- test/dummy/db/schema.rb
For: https://github.com/Shopify/maintenance_tasks/issues/342
Confirmed that the index on just `:task_name` is redundant given our composite index on `[:task_name, :created_at]`. We can remove it.
I think we need to remove the index from the table itself in a `change_table` block (instead of using https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-remove_index) due to LHM constraints (as mentioned [here](https://github.com/Shopify/maintenance_tasks/pull/239), modifying indexes outside of table blocks seems to pose problems for LHMs).
> Remove redundant index on :task_name

- lib/maintenance_tasks/engine.rb
When using the classic autoloader, simply by using a CSV Task, we got in the situation where we try to refer to CsvCollection but it hasn't yet been loaded.
Fixes #347.
> Eager-load the engine before the app code for the classic autoloader

- app/models/maintenance_tasks/progress.rb
- test/models/maintenance_tasks/progress_test.rb
When a Task is finished processing, but the `JobIteration.max_job_runtime` has been reached, the Task gets interrupted, then when it starts it finally gets marked as succeeded, because there's no additional element to process.
When that happens, the tick count is equal to the tick total and the progress bar appears as indefinite. We were missing a test at the boundary.
> Don't show indefinite progress bar when finishing a task

- app/jobs/maintenance_tasks/task_job.rb
- lib/maintenance_tasks.rb
- test/jobs/maintenance_tasks/task_job_test.rb
For: https://github.com/Shopify/maintenance_tasks/issues/335
This PR fixes a bug that occurs when a job gets interrupted and is reenqueued faster than the original job takes to shut down. This results in race conditions with the `@run` and results in errors due to invalid status transitions (and notably results in a run showing up as interrupted when it is actually running).
To solve this, we should delay reenqueuing the job until after all callbacks have completed, which can be done by calling `#reenqueue_iteration_job` in a prepended after_perform callback in TaskJob, and skipping the call that JobIteration performs in [`#iterate_with_enumerator`](https://github.com/Shopify/job-iteration/blob/ae9f11e316c99eaf0c5a478c1fa0a659fcd7730a/lib/job-iteration/iteration.rb#L131).
Arguably …
> Postpone reenqueuing the iteration job until after callbacks are done

- app/controllers/maintenance_tasks/application_controller.rb
- app/controllers/maintenance_tasks/runs_controller.rb
- app/controllers/maintenance_tasks/tasks_controller.rb
- app/helpers/maintenance_tasks/application_helper.rb
- app/helpers/maintenance_tasks/tasks_helper.rb
- app/models/maintenance_tasks/application_record.rb
- app/models/maintenance_tasks/csv_collection.rb
- app/models/maintenance_tasks/progress.rb
- app/models/maintenance_tasks/run.rb
- app/models/maintenance_tasks/task_data.rb
- app/models/maintenance_tasks/ticker.rb
- app/validators/maintenance_tasks/run_status_validator.rb
- lib/generators/maintenance_tasks/install_generator.rb
- lib/generators/maintenance_tasks/task_generator.rb
- lib/maintenance_tasks/cli.rb
- test/lib/maintenance_tasks_test.rb
This just make hard to use reflection on Ruby classes breaking tools like tapioca. The value we want to provide with this call is telling people to not use this class, but that is already achieved by `@api private`.
If people really want to use this constant even if we told them to not do it, isn't `private_constant` that will stop them.
> Avoid usage of private_constant

- app/models/maintenance_tasks/run.rb
- app/models/maintenance_tasks/task_data.rb
- app/views/maintenance_tasks/runs/_info.html.erb
Right now, both:
https://github.com/Shopify/maintenance_tasks/blob/0c5813cd2d5acd8a4457d9ddfe6072dd9bd48ed6/app/views/maintenance_tasks/runs/_info.html.erb#L12
and
https://github.com/Shopify/maintenance_tasks/blob/0c5813cd2d5acd8a4457d9ddfe6072dd9bd48ed6/app/models/maintenance_tasks/run.rb#L191
will blow up when called in an app that does not have ActiveStorage set up.
Arguably 
https://github.com/Shopify/maintenance_tasks/blob/0c5813cd2d5acd8a4457d9ddfe6072dd9bd48ed6/app/models/maintenance_tasks/run.rb#L189
and
https://github.com/Shopify/maintenance_tasks/blob/0c5813cd2d5acd8a4457d9ddfe6072dd9bd48ed6/app/models/maintenance_tasks/runner.rb#L48
also blow up, but these are scenarios where the app is attempting to use CSV functionality, so I think it's okay that these result in the missing …
> Check if ActiveStorage used before fetching Run's csv_file

- README.md
We should always start with a draft release, add to it as we make changes to the gem, and then publish it as a last step once we've deployed to Rubygems.
This PR updates the instructions in the README around releasing a new version.
> Update release instructions in the README

- db/migrate/20210225152418_remove_index_on_task_name.rb
Closes: https://github.com/Shopify/maintenance_tasks/issues/368
We have `">= 6.0"` set as the version requirement for `activerecord` in our gemspec, but since we've upgraded Rails to `6.1`, any migrations we generate are now versioned as `[6.1]`. This leads to incompatibilities with apps that are using `6.0`. 
Any migrations we generate moving forward should not exceed the minimum accepted ActiveRecord version as set by our gem specification.
> Use min accepted version for ActiveRecord::Migration classes

- README.md
- app/models/maintenance_tasks/run.rb
- lib/maintenance_tasks.rb
Closes: https://github.com/Shopify/maintenance_tasks/issues/369
Rails 6.1+ allows multiple services to be configured per environment for Active Storage. When [defining an attachment on a model](https://edgeapi.rubyonrails.org/classes/ActiveStorage/Attached/Model.html#method-i-has_one_attached), the `service` option can be used to specify which service config to use.
Let's allow users to specify which service to use for `csv_file` attachments on our `Run` model by making it a config option on the gem.
🎩 
```
MaintenanceTasks.active_storage_service = :local
```
Try running the `Maintenance::ImportPostsTask` and ensure that the blob gets uploaded to `test/dummy/storage` rather than `test/dummy/tmp/storage`.
> Allow configuration of Active Storage service

- Gemfile.lock
- app/controllers/maintenance_tasks/application_controller.rb
- app/controllers/maintenance_tasks/tasks_controller.rb
- app/helpers/maintenance_tasks/application_helper.rb
- app/models/maintenance_tasks/runs_page.rb
- app/views/maintenance_tasks/tasks/show.html.erb
- lib/maintenance_tasks.rb
- maintenance_tasks.gemspec
- test/helpers/maintenance_tasks/application_helper_test.rb
- test/models/maintenance_tasks/runs_page_test.rb
- test/system/maintenance_tasks/tasks_test.rb
Closes: https://github.com/Shopify/maintenance_tasks/issues/362
As mentioned in the issue, Pagy uses offset-based pagination, which decreases in performance as the collection of elements being paginated grows. It doesn't scale very well, and queries that use OFFSET are outright banned in Core for performance reasons. A cursor based pagination strategy queries based on a specific point in the dataset (the cursor), and works well for
sequential datasets / datasets with ordered attributes (`maintenance_tasks_runs` table is guaranteed to be sortable by `created_at` / `id`).
This PR introduces a `RunsPage` model that handles generating a "page" of `Runs` based on a cursor (`id`). Instead of calling `TaskData#previous_runs` and passing this to `pagy` to be paginated, the `TasksController#show` …
> Remove Pagy in favour of cursor-based pagination

- README.md
- app/jobs/maintenance_tasks/task_job.rb
- test/jobs/maintenance_tasks/task_job_test.rb
Closes: https://github.com/Shopify/maintenance_tasks/issues/374
Errors in a Task can occur _before_ the `before_perform` callback runs (ie. before `@run`) is set. The main scenario to be concerned about here is if deserializing the run fails (in the Partners app, this happened because the connection to the MySQL server was lost when attempting to deserialize). Another case to consider is that users might have a custom Job with a callback that raises for some reason, prior to our `TaskJob#before_perform` callback happening.
Right now, `on_error` blows up when `@run` is not defined. This leads to unintended consequences - namely, job retries happening that we are not in control of. The upside is that it makes the framework somewhat "resilient" (ie. the job might retry and succeed, leading …
> Handle no run when rescuing errors in TaskJob

- app/helpers/maintenance_tasks/tasks_helper.rb
- app/models/maintenance_tasks/progress.rb
- app/views/maintenance_tasks/runs/info/_running.html.erb
- test/helpers/maintenance_tasks/tasks_helper_test.rb
- test/models/maintenance_tasks/progress_test.rb
Having the elapsed ticks / total ticks hidden away in the title attribute of the progress bar is not very discoverable for users. For long-running tasks where progress is slow and not very obvious by the progress bar, it helps to see the tick count to have confidence that the Task is still progressing.
I've moved the progress info out of the `title` attribute of the `progress` element, and into a span underneath the progress bar. Changes are as follows:
- Renamed `Progress#title` to `Progress#text` since it's no longer really a title
- Cleaned up `Progress#text` a bit, and made the returned string more consistent (notably `Processed 10 out of 10 (100%)` => `Processed 10 out of 10 items (100%).`
- Changed `TasksHelper#progress` to return a div wrapping both the progress element and a span …
> Make progress information visible in the info card

- Gemfile.lock
- maintenance_tasks.gemspec
Draft release here: https://github.com/Shopify/maintenance_tasks/releases/edit/untagged-799da69791c7b7acc355
I decided to bump us up to v1.2.0 rather than v1.1.3, since we had a couple minor changes that were not strictly bug fixes.
> Bump gem to v1.2

- app/models/maintenance_tasks/run.rb
`v1.2.0` is broken for all Rails versions < 6.1.0 due to `has_one_attached: unknown keyword: service (ArgumentError)`, introduced [in this PR](https://github.com/Shopify/maintenance_tasks/pull/372).
~~Couldn't think of a better way to patch this and preserve functionality for Rails < 6.1.0 while allowing service configuration for Rails 6.1+ apps than checking the kwargs on the method and either passing in a service or not 😅  Let me know if you can think of a better way!~~
Opting instead to check for the presence of the `MaintenanceTasks.active_storage_service` config instead to check if we should specify the `service` kwarg, rather than doing parameter introspection.
I think we may also want to expand our test suite to test against a dummy app that use Rails 6.0, and then Rails 6.1 to …
> Maintain backwards compatibility when using #has_one_attached

- app/models/maintenance_tasks/run.rb
This allows loading the gem and running regular Tasks when `active_storage/engine` is not required in `config/application.rb`.
Not having required `active_storage/engine` will have the same result as having it required but not configured. An error is raised when a CSV file is uploaded, but no earlier.
This is handled in the README so I'm not sure we want to do more about this.
> Make Active Storage optional

- app/tasks/maintenance_tasks/task.rb
Instead of waiting until a CSV file is uploaded, this raises an exception early when a CSV Task is defined by calling `csv_collection` and Active Storage is not loaded or its tables created.
I reused part of the message that Rails emits when a file is attached and one of the Active Storage tables does not exist.
No tests because we load Active Storage in the dummy app, and I'm not sure it's worth adding a very slow test creating an app.
🎩 To tophat:
```sh-session
$ cd
$ rails new my_app --skip-active-storage && cd my_app
$ echo "gem 'maintenance_tasks', path: '../src/github.com/Shopify/maintenance_tasks'" >> Gemfile
$ bundle
$ rails g maintenance_tasks:install
$ rails g maintenance_tasks:task my_csv_task --csv
$ rails s
```
> Raise early when Active Storage is not setup

- Gemfile.lock
- gemfiles/rails_6_0.gemfile.lock
- gemfiles/rails_edge.gemfile.lock
- maintenance_tasks.gemspec
I noticed we weren't shipping the license file which I think we are supposed to. The gem wasn't specified as MIT-licensed either.
And a bump for making Active Storage optional.
> Release 1.2.2

- lib/generators/maintenance_tasks/templates/task_spec.rb.tt
Just a quick fix, we use the task_spec generator a lot and it is handy that it generates a few lines to get you started, so I thought we might as well be able to use those lines in our code rather than needing to delete them.
The current generator generates something like
```ruby
require 'rails_helper'
module Maintenance
RSpec.describe SomeMaintenanceTask do
end
end
```
If we're generating this starter code, I think we might as well generate it in a somewhat usable manner, rather than generating it for it to be deleted later 
This is a minor change but I just rearranged the .process and cleaned it up a bit so it matches up with the [RSpec/DescribedClass convention](https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/DescribedClass). The generator will now generate something like …
> Enhance usability of task_spec generator

- .github/workflows/ci.yml
This is almost identical to the change I made in https://github.com/Shopify/job-iteration/pull/74.
- Only run on push. Running on Pull Request seems redundant, since all PRs would include a push.
- Rename the workflow from "Ruby" to "CI" to avoid redundant prefix
- Append Gemfile from matrix to job name, so they are distinguishable
> Tweak workflow labelling and triggers

- .rubocop.yml
Since rubocop-shopify was using `DisabledByDefault`, simply adding the rules in our config enabled them, like the documentation explains:
> All cops are then disabled by default. Only cops appearing in user configuration files are enabled. `Enabled: true` does not have to be set for cops in user configuration. They will be enabled anyway.
But now rubocop-shopify moved to marking the specific rules as disabled instead, which does not enable them automatically when they are used.
So when I updated to 2.1.0 in #397, we inadvertently disabled those two.
> Re-enable Rubocop documentation rules

- README.md
- app/jobs/concerns/maintenance_tasks/task_job_concern.rb
- app/tasks/maintenance_tasks/task.rb
- test/dummy/app/tasks/maintenance/update_posts_throttled_task.rb
- test/jobs/maintenance_tasks/task_job_test.rb
- test/models/maintenance_tasks/task_data_test.rb
- test/system/maintenance_tasks/tasks_test.rb
- test/tasks/maintenance_tasks/task_test.rb
Closes: https://github.com/Shopify/maintenance_tasks/issues/298
I revisited adding throttling! I think adding a simple DSL like this optimizes for ease of use from a user's perspective:
```ruby
throttle_on -> { <condition> }, backoff: <backoff>
```
The PR is pretty simple - JobIteration's [Throttle Enumerator](https://github.com/Shopify/job-iteration/blob/4e4ed66c0c325d6e28ecddf84399f1b291ae8ae4/lib/job-iteration/throttle_enumerator.rb) does most of the work for us, so we just need to wrap the enumerator we build using the collection in a throttle enumerator Job Iteration constructs via [`#build_throttle_enumerator`](https://github.com/Shopify/job-iteration/blob/4e4ed66c0c325d6e28ecddf84399f1b291ae8ae4/lib/job-iteration/enumerator_builder.rb#L113)
As discussed in …
> Introduce Mechanism for Throttling

- README.md
- app/controllers/maintenance_tasks/tasks_controller.rb
- app/jobs/concerns/maintenance_tasks/task_job_concern.rb
- app/models/maintenance_tasks/run.rb
- app/models/maintenance_tasks/runner.rb
- app/models/maintenance_tasks/task_data.rb
- app/tasks/maintenance_tasks/task.rb
- app/views/maintenance_tasks/tasks/show.html.erb
- db/migrate/20210517131953_add_arguments_to_maintenance_tasks_runs.rb
- test/application_system_test_case.rb
- test/dummy/app/tasks/maintenance/params_task.rb
- test/dummy/db/schema.rb
- test/jobs/maintenance_tasks/task_job_test.rb
- test/models/maintenance_tasks/run_test.rb
- test/models/maintenance_tasks/runner_test.rb
- test/models/maintenance_tasks/task_data_test.rb
- test/system/maintenance_tasks/runs_test.rb
- test/system/maintenance_tasks/tasks_test.rb
- test/tasks/maintenance_tasks/task_test.rb
Closes: https://github.com/Shopify/maintenance_tasks/issues/406, https://github.com/Shopify/maintenance_tasks/issues/325
This PR introduces support for custom Task parameters by leveraging `ActiveModel` attributes & validations.
Task authors use `ActiveModel::Attributes` for their parameters, and can define their own validations to ensure any parameters that are passed from the UI conform to their expectations (ie. `Maintenance::ParamsTask` uses a presence validator and a regex to ensure that post ids is a comma-delimited list of integers).
- `MaintenanceTasks::Task` includes relevant `ActiveModel` modules
- In the view, we render a text field for every parameter the Task supports
- These params are passed from controller => `Runner#run`. `MaintenanceTasks::Run` has a field for …
> Support Tasks with custom parameters

- test/dummy/db/schema.rb
SQLite dumps bigint columns as integer columns in the database schema, even if they should really be bigints for other adapters because they're the primary keys of other tables.
🎩 
```sh-session
$ bundle add mysql2
$ export DATABASE_URL=mysql2://root@localhost/maintenance_tasks_development
$ rails db:setup
```
This blows up on main with:
```
Created database 'maintenance_tasks_development'
rails aborted!
ActiveRecord::MismatchedForeignKey: Column `blob_id` on table `active_storage_attachments` does not match column `id` on `active_storage_blobs`, which has type `bigint`. To resolve this issue, change the type of the `blob_id` column on `active_storage_attachments` to be :bigint. (For example `t.bigint :blob_id`).
Original message: Mysql2::Error: Referencing column 'blob_id' and referenced …
```
> Fix schema for MySQL

- app/models/maintenance_tasks/runner.rb
- test/models/maintenance_tasks/runner_test.rb
When wrapping this gem for Shopify/shopify, we want to get the newly created or resumed `Run` from `Runner.run`.
This yields the current run only if a block is passed to `Runner.run`, without documenting that feature since `Run` is a private API that most apps shouldn't tinker with.
Fixes #405
> Yield the run in `Runner.run`

- test/dummy/config/initializers/content_security_policy.rb
It has been superseded by Content-Security-Policy: frame-ancestors, which is widely supported:
https://caniuse.com/mdn-http_headers_csp_content-security-policy_frame-ancestors
Now Chrome has added a warning:
The page delivered both an 'X-Frame-Options' header and a
'Content-Security-Policy' header with a 'frame-ancestors'
directive.  Although the 'X-Frame-Options' header alone would
have blocked embedding, it has been ignored.
The warning is confusing because the X-Frame-Options header alone would not have blocked embedding, because Rails defaults to SAMEORIGIN which allows embedding in the same site like we do here.
This only removes the header from the dummy app for tests.
> Remove X-Frame-Options header from dummy application

- README.md
- app/controllers/maintenance_tasks/tasks_controller.rb
- app/models/maintenance_tasks/run.rb
- lib/maintenance_tasks/cli.rb
- test/lib/maintenance_tasks/cli_test.rb
- test/models/maintenance_tasks/run_test.rb
Follow up to https://github.com/Shopify/maintenance_tasks/pull/413
The final piece of supporting Tasks with custom parameters in the gem - this allows arguments to be specified via the CLI using an `--arguments` flag.
As discussed [here](https://github.com/Shopify/maintenance_tasks/pull/413#discussion_r640906234), the use of Strong Parameters in TasksController to permit only keys matching the Task's attributes is a bit problematic because it results in a 500 instead of alerting the user. We also wanted to apply this same behaviour to the CLI. As such, I moved the check on the argument keys out of the controller and [into `task.rb`](https://github.com/Shopify/maintenance_tasks/pull/428/files#diff-12c4b871a85e4070bcce611251c906b2be70f1cedbcb373ca066e9759f951d28R278-R285). However, I'm not …
> Support Tasks with Params with CLI

- README.md
- test/dummy/config/application.rb
This comes up a fair amount at Shopify, since many large Rails apps roll up their db migrations. It's reasonable to assume that external applications using this gem may be doing a similar thing.
We discussed trying to be smarter about figuring out which migrations an app already ran and only copying over necessary ones, which spawned [this issue](https://github.com/Shopify/maintenance_tasks/issues/441), but it's a pretty involved solution for the size of the problem.
A quick fix that makes the user experience better is laid out in this PR. If an app has rolled up past MT migrations, they are advised to run the migration copying subcommand, remove any unnecessary migrations (by checking the release notes to see which ones have been added since the last upgrade) and then manually running …
> Add note on handling rolled-up migrations to the README

- app/models/maintenance_tasks/run.rb
- test/models/maintenance_tasks/run_test.rb
- test/system/maintenance_tasks/runs_test.rb
Closes: #448 
We need a way to synchronize changes to the stuck task timer if an application decides to extend the gem. At the moment if both applications are using 5 minutes for a stuck timeout but there could be consequences if these changed. (I.e in the gem but not the application based off it.
I.e if we changed the timer to one min and another application has the old timeout (5 minutes).
> Add constant for stuck task timeouts

- app/jobs/concerns/maintenance_tasks/task_job_concern.rb
- test/jobs/maintenance_tasks/task_job_test.rb
Compatibility with the blackhole system in Shopify/shopify requires us to have the `job_id` available on the `MaintenanceTasks::Run` as soon as it's enqueued, not once it's about to start performing.
This PR simply changes the deserialization of the `MaintenanceTasks::Run` + the setting of `job_id` on the run to happen in a `before_enqueue` block rather than in the `before_perform` block.
> Persist `job_id` to Run before job is enqueued

- app/views/maintenance_tasks/runs/_info.html.erb
- test/system/maintenance_tasks/runs_test.rb
Closes: https://github.com/Shopify/maintenance_tasks/issues/447
Shows the arguments a Task was run with in the UI.
🎩 
**Index page**
**Show page (latest Run)**
**Show page (previous Runs)**
Is this the best way to present this information?
> Show Run arguments in UI

- app/views/maintenance_tasks/runs/_arguments.html.erb
- app/views/maintenance_tasks/runs/_csv.html.erb
- app/views/maintenance_tasks/runs/_info.html.erb
- app/views/maintenance_tasks/runs/_run.html.erb
- app/views/maintenance_tasks/runs/info/_errored.html.erb
- app/views/maintenance_tasks/tasks/_task.html.erb
- app/views/maintenance_tasks/tasks/show.html.erb
- test/system/maintenance_tasks/runs_test.rb
Some slight improvements to the Task show page for Tasks with arguments / CSVs:
**Before**
**After**
**Before**
**After**
**Before**
**After**
----------------------
----------------------
(Long content is scrollable)
> Style Task arguments section better

- Gemfile.lock
- README.md
- maintenance_tasks.gemspec
I'm proposing we release a new version now so we can start tackling some of the changes in Shopify/shopify 😄 
We can cut a `v.1.5.1` later to address fixing `job_id` to be set on insert instead of update, as well as to allow collections that support objects responding to `to_enum` to finish up CSV support.
Drafted release notes: https://github.com/Shopify/maintenance_tasks/releases/edit/untagged-a14428f6d5f7d26e76bc
> Bump version to 1.5.0

- README.md
- app/models/maintenance_tasks/runner.rb
- test/models/maintenance_tasks/runner_test.rb
- test/system/maintenance_tasks/runs_test.rb
In #318 we wanted to change the name of CSV files, but the added complexity wasn't worth it because we were adding a controller to provide the file name.
This changes the name before uploading, that way files also have useful names in the Active Storage service, not only when downloading them with the UI.
> Change the name of the CSV file before uploading

- app/jobs/concerns/maintenance_tasks/task_job_concern.rb
- app/models/maintenance_tasks/csv_collection_builder.rb
- app/models/maintenance_tasks/null_collection_builder.rb
- app/models/maintenance_tasks/run.rb
- app/models/maintenance_tasks/task_data.rb
- app/tasks/maintenance_tasks/task.rb
- test/models/maintenance_tasks/csv_collection_builder_test.rb
- test/models/maintenance_tasks/null_collection_builder_test.rb
We want to add more ways to build collection, so using a strategy
pattern makes sense since we don't need to be including different
modules with different API and we can just swap the strategy at
runtime.
> Change CSV collection implementation to use a strategy pattern.

- app/models/maintenance_tasks/run.rb
- test/jobs/maintenance_tasks/task_job_test.rb
- test/models/maintenance_tasks/run_test.rb
Currently, if a Task raises prior to the `#on_start` callback running (for example, if there is a problem with `#collection` and it raises), no `started_at` timestamp gets set on the `Run`. 
I think it's kind of weird to have an `ended_at` timestamp on a complete `Run`, but no `started_at` timestamp. IMO if a `Run` is `completed?` we should be able to assume that both those timestamps are present.
> Set `started_at` on `MaintenanceTasks::Run` if error occurs before `#on_start`

- lib/generators/maintenance_tasks/templates/task.rb.tt
The README makes it clear that `#process` needs to be idempotent. There are potentially major consequences of not adhering to this recommendation. We should remind developers inline while they are writing the `#process` method. 
The generated task file includes help comments already. I've extended them to include the idempotency hint.
> Include idempotency hint in generated task template.

- Rakefile
When I run `bundle exec rake` the tests fail, and it has been happening since #470.
It comes from https://github.com/rubocop/rubocop/pull/10000.
Parallelization causes issues with the way Rails runs tests see https://github.com/rails/rails/pull/41132, since Rails uses `at_exit`, and Rubocop creates multiple forks, all of them start running the tests, and database locking occurs.
We could also fix that by moving the Rubocop task first, since the `at_exit` hooks wouldn't have been defined at this point, but I like to keep it at the end, and it's not that slow anyway. It could also be fixed by Rubocop not running its code directly from the Rake task, but in a subprocess, which would not bring along the `at_exit` hooks.
> Don't run rubocop in parallel with the Rake task

- README.md
- app/jobs/concerns/maintenance_tasks/task_job_concern.rb
- app/models/maintenance_tasks/task.rb
- test/dummy/app/tasks/maintenance/callback_test_task.rb
- test/jobs/maintenance_tasks/task_job_test.rb
- test/models/maintenance_tasks/task_data_test.rb
- test/models/maintenance_tasks/task_test.rb
- test/system/maintenance_tasks/tasks_test.rb
Closes #334 
Having callbacks provides the client the opportunity to integrate with the task lifecycle. As cited in the original issue, a Slack notification (or any other message dispatch) seems to be a common use case when running tasks such as these.
This PR adds an interface for supporting callbacks in `MaintenanceTasks::Task`. 
It provides the following public class methods: 
- `after_start`
- `after_pause`
- `after_interrupt`
- `after_error`
- `after_cancel`
- `after_complete`
One important behaviour is that errors that are raised during the custom error callback code are **ignored / swallowed**, to guarantee that our `error_handler` proceeds as expected.
Internally, the events added to the object lifecycle are: `start`, `complete`, `pause,` `interrupt`, `cancel`, `error`.
The …
> Introduce callbacks for Task lifecycle

- app/models/maintenance_tasks/task.rb
Closes https://github.com/Shopify/maintenance_tasks/issues/488
Checks for Active Storage during `csv_file` call instead of during evaluation time of a `csv_collection` task. We don't appear to test this.
> Raise Active Storage error in CSV collection method

- README.md
- app/models/maintenance_tasks/runner.rb
- app/models/maintenance_tasks/task.rb
- test/dummy/app/jobs/another_custom_task_job.rb
- test/dummy/app/tasks/maintenance/custom_job_task.rb
- test/models/maintenance_tasks/runner_test.rb
- test/models/maintenance_tasks/task_data_test.rb
- test/models/maintenance_tasks/task_test.rb
- test/system/maintenance_tasks/tasks_test.rb
To support tasks in the global ("master") context in Shopify/shopify, we need to use a separate job class that disables all of the automatic pod selection logic. This is done at load time, so I don't think there's a way to handle this other than using distinct job classes to handle non-podded vs podded tasks.
One possible way to accomplish this is to inject the job class into the runner, just as we're doing with the `run_model`. See https://github.com/Shopify/maintenance_tasks/pull/498/commits/1cce03d2cac084dd2a7a7c8342d5007b495bcb50
However, we'd [previously discussed](https://github.com/Shopify/maintenance_tasks/pull/96#pullrequestreview-517821649) allowing job classes to be configured on a per-task basis, so I figured I'd put this up and see how we felt about it. IMO, while allowing …
> Make Job class configurable per Task

- app/models/maintenance_tasks/run.rb
- test/dummy/app/jobs/custom_task_job.rb
- test/jobs/maintenance_tasks/task_job_test.rb
- test/models/maintenance_tasks/run_test.rb
Follow-up to #515
First, we can entirely avoid the "optimistic update" if the run is already stopping, like we were doing before in the non-race-condition case.
Also, since we know whether or not the record was updated, we know it was indeed stopping (but not its actual status), so we can prevent even a single iteration from happening (but we have to reload to get the actual status to either moved to paused or cancelled).
I tested the first point by re-using `count_uncached_queries`.
For the second point, I tested it by simulating a race condition for the model, but I also added a test at the job level for good measure. It also causes the race condition by running in a `before_perform` callback. This runs after Active Job deserializing the Run, but since it's prepended, before …
> Avoid iteration for stopping race condition

- Gemfile.lock
- maintenance_tasks.gemspec
We're hoping to use commit https://github.com/Shopify/maintenance_tasks/commit/de3a0b990430b32a0a892b32d5f5af18dc976466, but would prefer not to tag to a specific commit in our repository. It looks like the last version bump was in July, so I figured it's worth putting out a new version. Let me know if I missed anything!
> Bump version to 1.6.0 so we can put out a release

- test/application_system_test_case.rb
Since it's due to Rails' system tests and fixed there for Rails 7, we can ignore the warning for previous versions.
> Ignore Selenium warning we don't control

- README.md
- lib/maintenance_tasks/engine.rb
- test/dummy/config/application.rb
Reverts Shopify/maintenance_tasks#529
We can revert this revert once we've properly deprecated classic autoloading.
> Revert "Drop support for classic autoloading"

- app/models/maintenance_tasks/task_data.rb
- test/dummy/app/tasks/maintenance/update_posts_module_prepended_task.rb
- test/dummy/lib/test_module.rb
- test/models/maintenance_tasks/task_data_test.rb
- test/models/maintenance_tasks/task_test.rb
- test/system/maintenance_tasks/tasks_test.rb
Preamble: I'm not sure this is something that you all would like to support (especially since it adds Sorbet as a development/test dependency just to support the test). I figured I'd open the pull request and if it should be closed right away, that's fine from my side! 🎉 
Please let me know if I've missed any steps or if this is the wrong approach. If there are additional changes you'd like, I'm more than happy to make them as well. Thank you!
Gem versions: `1.5.0`, `1.6.0`
Ruby versions: `2.7.2`, `3.0.2p107`
Rails versions: `6.0.4`, `6.1.4.1`
After creating a new task recently (and with `sorbet-runtime` enabled), I noticed that the source code display in the UI returns source for [Sorbet's `T::Private::Methods` module](https://github.com/sorbet/sorbet/blob/master/gems/sorbet-runtime/lib/t …
> Support Sorbet-annotated task code display in task UI

- app/helpers/maintenance_tasks/tasks_helper.rb
- app/views/maintenance_tasks/tasks/show.html.erb
- test/dummy/app/tasks/maintenance/params_task.rb
- test/helpers/maintenance_tasks/tasks_helper_test.rb
- test/models/maintenance_tasks/task_data_test.rb
- test/system/maintenance_tasks/tasks_test.rb
Addresses - https://github.com/Shopify/maintenance_tasks/issues/485
Currently blank attribute values passed from the form override all default values
The solution is far from being perfect but seems to be the most reasonable from UX point of view.
It seems helpful to render default values on the form so anyone can be aware of them just by looking on the UI 
Example:
Using an instance of a task class seems to be the most appropriate and most publicly available API at the moment to get default values
> Render task default attributes on the form

- app/helpers/maintenance_tasks/tasks_helper.rb
- app/models/maintenance_tasks/task_data.rb
- app/views/maintenance_tasks/tasks/show.html.erb
- test/helpers/maintenance_tasks/tasks_helper_test.rb
- test/models/maintenance_tasks/task_data_test.rb
Follow up to #532
I feel like the presenter is a good place to deal with this, TaskData takes the place of a Task class in views (we even call its instance `@task`), so since we want `Task.new` to instantiate a task and get its attributes for defaults, we can use instead `TaskData#new`.
Also added an edge case about deleted Tasks. It's not strictly necessary since `parameter_names` is empty when the task is deleted, and we don't show the form and instantiate the Task in that situation, but it's more for completeness.
> Move Task instantiation to TaskData

- README.md
- app/models/maintenance_tasks/csv_collection_builder.rb
Clarify that CSV uploads must have a newline at the end of the file for counts to be accurate.
> Clarify newline must be at EOF of CSV

- app/jobs/concerns/maintenance_tasks/task_job_concern.rb
- app/models/maintenance_tasks/run.rb
- db/migrate/20211210152329_add_lock_version_to_maintenance_tasks_runs.rb
- test/dummy/app/jobs/custom_task_job.rb
- test/dummy/db/schema.rb
- test/jobs/maintenance_tasks/task_job_test.rb
- test/models/maintenance_tasks/run_test.rb
Take 2 of https://github.com/Shopify/maintenance_tasks/pull/178
Data races are a problem in the gem because:
1) We update the status of a `MaintenanceTasks::Run` object frequently as it progresses through the lifecycle of a Task, and
2) A `run` is updated by a running `TaskJob`, but also by the controller when pausing / resuming / cancelling a Task. This can create race conditions between writes. The primary scenario is that the `@run` in the job gets "stale" if a write happens between when we read the status value for an in-memory run object (where this value determines what status we should write), and when we actually perform the write.
Why is this a problem?
- It can lead to tasks not getting cancelled properly. If an interrupt happens at the same time as the task is cancelled, the …
> Optimistic locking + fix data races

- app/views/maintenance_tasks/runs/_run.html.erb
- app/views/maintenance_tasks/tasks/_task.html.erb
- app/views/maintenance_tasks/tasks/show.html.erb
The work done on #559 added the ability of hosting apps to use a block to wrap around `TasksController#run` if so they wish. That works very well in the backend, but the views won't be able to display extended/custom information managed by hosting apps. One way would be to completely rewrite the views, but what if the default views are good enough and users just wanted to inject a little piece of additional info into the engine's own views?
This draft's intent is to gather feedback on how this could be done. The suggestion here is to use empty partials that are rendered by the engine and overridden in the hosting app. I am not sure if the placement of those partials is correct or even if this is a good idea at all. The screenshot below shows how that could look like (for both displaying …
> Introduce empty partials for apps to extend views

- app/models/maintenance_tasks/run.rb
- test/models/maintenance_tasks/run_test.rb
Closes #493 to prevent [errors](https://app.bugsnag.com/shopify/arrive-server/errors/61fd2678bb89340008de6f8c?filters[search]=ActiveRecord%3A%3AValueTooLong) like:
```
ActiveRecord::ValueTooLongMaintenanceTaskJob@default
Mysql2::Error: Data too long for column 'error_message' at row 1
```
How I have 🎩'd it:
```
$ bundle add mysql2
$ export DATABASE_URL=mysql2://root@localhost/maintenance_tasks_development
$ brew services start mysql
$ bundle exec rails db:setup
$ bin/rails app:db:environment:set RAILS_ENV=test
$ bundle exec rails test
```
🎉
> Truncate the error message when message is too long

- README.md
- app/jobs/concerns/maintenance_tasks/task_job_concern.rb
- app/models/maintenance_tasks/csv_collection_builder.rb
- app/models/maintenance_tasks/no_collection_builder.rb
- app/models/maintenance_tasks/null_collection_builder.rb
- app/models/maintenance_tasks/task.rb
- lib/generators/maintenance_tasks/task_generator.rb
- lib/generators/maintenance_tasks/templates/no_collection_task.rb.tt
- lib/generators/maintenance_tasks/templates/no_collection_task_test.rb.tt
- test/dummy/app/tasks/maintenance/no_collection_task.rb
- test/jobs/maintenance_tasks/task_job_test.rb
- test/lib/generators/maintenance_tasks/task_generator_test.rb
- test/models/maintenance_tasks/task_data_test.rb
- test/models/maintenance_tasks/task_test.rb
- test/system/maintenance_tasks/tasks_test.rb
Closes: https://github.com/Shopify/maintenance_tasks/issues/568
Sometimes, a Task may simply need to perform an action without iterating over multiple elements in a collection. For example, a Task might need to kick off another job, interact with a third-party API, or perform a single operation. This adds support for "collection-less" tasks, which need only to define a `#process` method.
I'm proposing an API similar to what we've done for `csv_collection` tasks, where we use a `no_collection` macro in the task. Under the hood, we can use a `NoCollectionBuilder` to handle defining `#collection` and `#count` (with collection simply being `:no_collection` for use when building the enumerator), and in the job we can use Job Iteration's `#build_once_enumerator` to handle this.
I've added a …
> Support Tasks that perform a single iteration

- app/models/maintenance_tasks/run.rb
Follow up to https://github.com/Shopify/maintenance_tasks/pull/494
This prevents us from upgrading the gem in Shopify/shopify, because `MaintenanceTasks::Run` is abstract + not backed by a table. We need to use `self.class` instead.
> Remove direct reference to MaintenanceTasks::Run in `#truncate` method

- Gemfile.lock
- app/jobs/concerns/maintenance_tasks/task_job_concern.rb
- maintenance_tasks.gemspec
- test/jobs/maintenance_tasks/task_job_test.rb
Currently throttling relies on the Enumerator enqueuing a job, which is problematic if we don't want to re-enqueue because the run is stopping (pausing or cancelling). This is shown in the new test which fails on main. The run is properly cancelled, but there's an enqueued job which then fails because it tries to move the run from cancelled to running.
This adds a conditional in the `after_perform` callback when we enqueue the job, to not do so when the run is stopped (at this point we've transitioned from _stopping_ to _stopped_.
This only works if we also change job-iteration to use the same `reenqueue_iteration_job` method for throttling, which is done in https://github.com/Shopify/job-iteration/pull/190.
If that PR gets merged, I'll release a new version and update this PR to require …
> Don't re-enqueue stopped throttled jobs

- README.md
- app/jobs/concerns/maintenance_tasks/task_job_concern.rb
- app/models/maintenance_tasks/batch_csv_collection_builder.rb
- app/models/maintenance_tasks/task.rb
- test/dummy/app/tasks/maintenance/batch_import_posts_task.rb
- test/jobs/maintenance_tasks/task_job_test.rb
- test/models/maintenance_tasks/task_data_test.rb
- test/models/maintenance_tasks/task_test.rb
- test/system/maintenance_tasks/tasks_test.rb
Closes: https://github.com/Shopify/maintenance_tasks/issues/601
This PR adds support for batch-processing CSV rows in a task by extending the existing `csv_collection` macro to take an `in_batches` option . Arrays of `CSV::Row` objects are then passed as input to the task's `#process` method.
Job Iteration already has [support for iterating over CSVs in batches](https://github.com/Shopify/job-iteration/blob/2e29ba910b7b97bfbe318a97e33918638dfd2d36/lib/job-iteration/csv_enumerator.rb#L39-L47), so our `#build_enumerator` method simply needs to hit job-iteration's `#batches` API to achieve this.
🎩 
- `bin/rails s`
- Navigate to http://127.0.0.1:3000/maintenance_tasks/tasks/Maintenance::BatchImportPostsTask
- Upload `test/fixtures/files/sample.csv`
- Run the task
> Support processing CSVs in batches

- lib/generators/maintenance_tasks/templates/no_collection_task_test.rb.tt
- lib/generators/maintenance_tasks/templates/task_spec.rb.tt
- lib/generators/maintenance_tasks/templates/task_test.rb.tt
While Rubocop always autocorrects it after the tests are generated:
`Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping` 
I figured I'd update the templates to match our style guide and prefer double-quoted strings, and save Rubocop some work
> update templates to prefer double-quoted strings

- app/controllers/maintenance_tasks/application_controller.rb
- app/controllers/maintenance_tasks/tasks_controller.rb
- app/views/layouts/maintenance_tasks/application.html.erb
Co-authored-by: Étienne Barrié <etienne.barrie@shopify.com>
Closes: https://github.com/Shopify/maintenance_tasks/issues/510, https://github.com/Shopify/maintenance_tasks/issues/569
This is an alternative approach to page refreshing, that should solve some of the complaints folks had with the meta tag usage (losing search abilities, making it difficult to copy/paste text, etc.)
We don't want to jump straight to Turbo for a couple of reasons:
- We'd need to make it an explicit dependency / configure it properly for support in pre Rails 7 apps
-  The gem doesn't use any assets currently / doesn't force embedding apps to use the asset pipeline, so it's tricky make the JS component for Turbo work
- Turbo includes a lot of stuff we don't need to achieve the desired behaviour (page refreshing) …
> Refresh by replacing document body instead of using header

- README.md
- lib/maintenance_tasks/engine.rb
- test/dummy/config/application.rb
In https://github.com/Shopify/maintenance_tasks/commit/c11faffc00218cb703e804444a83ced2d0e21cd8 we accidentally broke classic autoloading by referencing `CsvCollectionBuilder`. This made me remember that we should have removed support for this it several releases ago anyway. 
Yes, we could instead make it clearer that we need to reference `MaintenanceTasks::CsvCollectionBuilder` in a fully qualified way, but I think since classic autoloading is deprecated both in Rails and the gem, we can just remove it now.
Closes https://github.com/Shopify/maintenance_tasks/issues/528
> Drop support for classic autoloading

- lib/generators/maintenance_tasks/templates/no_collection_task_test.rb.tt
- lib/generators/maintenance_tasks/templates/task_spec.rb.tt
- lib/generators/maintenance_tasks/templates/task_test.rb.tt
What are you trying to accomplish?
When using the generator to create a new maintenance task and an associated spec I get a rubocop warning about having to add a new line "RuboCop: Add an empty line after magic comments. [Layout/EmptyLineAfterMagicComment]"
> add an extra line in rspec template to avoid rubocop errors

- app/models/maintenance_tasks/run.rb
- app/views/maintenance_tasks/tasks/show.html.erb
- lib/maintenance_tasks/cli.rb
- test/fixtures/files/sample.tsv
- test/models/maintenance_tasks/run_test.rb
- test/models/maintenance_tasks/runner_test.rb
Co-authored-by: @promulo 
Closes #443 
Fails early when the content type is not a "text/csv"
We are setting the CLI `content_type` to be "text/csv" because unlike on the controller, the CLI csv_file is a hash.
> Fail on invalid CSV content type

- app/controllers/maintenance_tasks/runs_controller.rb
- app/controllers/maintenance_tasks/tasks_controller.rb
- app/models/maintenance_tasks/run.rb
- app/models/maintenance_tasks/runner.rb
- app/models/maintenance_tasks/task_data.rb
- app/views/maintenance_tasks/runs/_run.html.erb
- app/views/maintenance_tasks/tasks/show.html.erb
- db/migrate/20220713131925_add_index_on_task_name_and_status_to_runs.rb
- test/dummy/db/schema.rb
- test/fixtures/maintenance_tasks/runs.yml
- test/models/maintenance_tasks/run_test.rb
- test/models/maintenance_tasks/runner_test.rb
- test/models/maintenance_tasks/task_data_test.rb
- test/system/maintenance_tasks/runs_test.rb
- test/system/maintenance_tasks/tasks_test.rb
Currently, only one task run can be active (running or paused) at a given time. This PR intends to add support for multiple runs for a given task to the gem.
The approach here was to introduce as least disruption as possible and implement minimal changes to both backend and UI, still adhering to current patterns. The dashboard and individual task pages were tweaked a bit in order to allow displaying more than one run for the same task. This means we should rely less on the concept of _last run_ and more on _active runs_.
I haven't experienced issues when manually testing this. Multiple task runs can be triggered using the usual _Run_ button and individual runs can be paused and resumed accordingly.
This is how the "new" index page looks like with these changes (the list of "New Tasks" and …
> Add support for multiple runs per task

- app/models/maintenance_tasks/run.rb
- test/jobs/maintenance_tasks/task_job_test.rb
- test/models/maintenance_tasks/run_test.rb
Closes: https://github.com/Shopify/maintenance_tasks/issues/687
Callback errors should be allowed to bubble up, halting task execution
and triggering the error handler. We should only rescue errors raised
in the `after_error` callback, since these are not handled any other way.
We _do_ need to rescue `Task::NotFound` errors though, in case a Task is deleted in the middle of running.
> Don't rescue callback errors

- app/controllers/maintenance_tasks/runs_controller.rb
- app/controllers/maintenance_tasks/tasks_controller.rb
- app/views/maintenance_tasks/tasks/show.html.erb
- config/routes.rb
Closes: https://github.com/Shopify/maintenance_tasks/issues/671
Instead of using a custom tasks#run route, we should move this action to the RunsController as runs#create, taking advantage of conventional CRUD operations.
Note that this will be a breaking change for apps who are patching the `TasksController` to provide a block for `tasks#run` (see https://github.com/Shopify/maintenance_tasks/pull/559). We may need to follow up with these apps after the 2.0 release.
> Use resourceful route for running a Task

- .github/workflows/ci.yml
- Gemfile
- Gemfile.lock
Ruby 2.7 stdlib's net-http, loaded by capybara, loads net/protocol from the stdlib ([with require_relative](https://github.com/ruby/ruby/blob/v2_7_6/lib/net/http.rb#L23)), and then we get [warnings for re-defining constants](https://github.com/Shopify/maintenance_tasks/actions/runs/3174329071/jobs/5170982966#step:7:8) when loading the gem version from net-smtp.
This fixes it by also using net-http as a gem, which since 3.0 loads it correctly with `require "net/protocol"`
Resolves #707 
It was also necessary to update rubygems for Ruby 2.7, otherwise there was an issue of stdlib's uri being loaded before the gem.
> Prevent double loading of net-protocol in Ruby 2.7

- app/controllers/maintenance_tasks/tasks_controller.rb
- app/models/maintenance_tasks/task_data_show.rb
- app/views/maintenance_tasks/tasks/show.html.erb
- test/models/maintenance_tasks/task_data_show_test.rb
Fixes https://github.com/Shopify/maintenance_tasks/issues/677
Since we're paginating, we're already loading the completed runs, so we can avoid one query by checking there's either an active run or a completed run before checking if it's a deleted task.
This is done by inlining TaskDataShow.find into the controller and then moving the Task.named call at the very last moment.
This has a small implication, if you "paginate" past the last cursor of a deleted task, you'll get a 404 instead of the empty task page with the last run at the top. This is not accessible via links anyway so it's fine.
Co-authored-by: Adrianna Chang <adrianna.chang@shopify.com>
> Remove EXISTS query on tasks#show

- test/helpers/maintenance_tasks/tasks_helper_test.rb
Generating a signed ID for the URL for an Active Storage Blob now requires that it's persisted.
https://github.com/rails/rails/pull/47027
> Fix test on Rails edge

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- Gemfile
- Gemfile.lock
- gemfiles/postgresql.gemfile
PosgreSQL is not an actual development requirement for this gem and asking everyone to install it only discourages contributions and make it less approachable for cloud-based environments like codespaces.
For many parts of the maintenance tasks even an in-memory `sqlite` database will suffice. 
So this PR removes the `pg` gem from the `Gemfile` and moves it to a separate gemfile which will be used on CI only.
> Remove `pg` gem as a development requirement

- .github/workflows/ci.yml
- gemfiles/rails_7_0.gemfile
- test/test_helper.rb
Additions to the CI:
`Ruby 3.2` - Just a new ruby version
`Rails 7` - Every day Rails 7 differs from rails edge more and more and now it's actually closer to Rails 7.1 so I would like to test specifically against Rails 7.
❓ 
- Ruby 2.7 has end of life in a few month. I don't think it means we should drop the support right now but we might want to do it soon
> Add Rails 7 and Ruby 3.2 to ci matrix

- test/application_system_test_case.rb
- test/test_helper.rb
`Selenium::WebDriver::Remote::COMMANDS` does not exist but instead it's `Selenium::WebDriver::Remote::Bridge::COMMANDS,` defined in `selenium/webdriver/remote/commands`
https://github.com/SeleniumHQ/selenium/blob/selenium-4.7.1-ruby/rb/lib/selenium/webdriver/remote.rb#L30
I'll rebase once #757 is merged.
> Remove silenced warning by requiring necessary file

- app/views/layouts/maintenance_tasks/application.html.erb
Quick upgrade of Bulma from 0.9.3 to 0.9.4.
https://github.com/jgthms/bulma/releases/tag/0.9.4
🎩 🎩 🎩 🎩 🎩
> Upgrade Bulma CSS from 0.9.3 to 0.9.4

- test/test_helper.rb
We still have to support 7.0 and below.
> Handle Rails 7.1 deprecation of TestFixtures#fixture_path

- README.md
- app/models/maintenance_tasks/task.rb
- test/dummy/app/tasks/maintenance/nested/nested_more/nested_more_task.rb
- test/dummy/app/tasks/maintenance/nested/nested_task.rb
- test/models/maintenance_tasks/task_data_index_test.rb
- test/models/maintenance_tasks/task_test.rb
- test/system/maintenance_tasks/tasks_test.rb
In [shop-server](https://github.com/Shopify/shop-server/tree/main/app/tasks/maintenance) we have tasks which are in sub-folders (e.g. `app/tasks/maintenance/deep_understanding`). These are available in production, but in development they are not automatically loaded, making them harder to test (TODO: verify this).
Before this PR, only tasks directly under `app/tasks` will be loaded in development. After this commit, one level of nesting is supported.
> Allow tasks to be loaded from nested task directories

- app/controllers/maintenance_tasks/runs_controller.rb
@adrianna-chang-shopify this is what I asked about earlier today - technically SQLite does have a limit (default of 1 billion bytes), but trying that breaks Selenium.
> Fix parameter name when creating a run fails due to an argument that's too long

- Gemfile
- Gemfile.lock
selenium-webdriver 4.9.1 is incompatible with the latest capybara
#818
> Lock selenium-webdriver to 4.9.0

- README.md
- app/controllers/maintenance_tasks/application_controller.rb
- lib/maintenance_tasks.rb
- test/documentation_test.rb
Add `MaintenanceTasks.parent_controller` configuration applications can assign the parent controller for the `maintenance_tasks` web UI. It defaults to `"ActionController::Base"` providing a flexible but non-breaking change.
This change allows applications with common logic in their `ApplicationController` (or any other controller) to optionally configure this web UI to inherit that logic with a simple assignment in the initializer.
eg.
`MaintenanceTasks.parent_controller = 'ApplicationController'`
Many applications rely on every controller inheriting from their `ApplicationController` to provide consistency in pre/post processing, security, logging, etc.
Currently, because all controllers for this web UI inherit from `MaintenanceTasks::ApplicationController` (which inherits from …
> Add `parent_controller` configuration option

- app/controllers/maintenance_tasks/application_controller.rb
The need for a nonce was removed in 3ba21de59b76b60335988eff2b08db0c51d542d6.
Rails needs to generate the nonce to put in the headers, even if nothing uses it later.
Before:
```sh-session
$ curl localhost:3000/maintenance_tasks -sD - | grep Content-Security-Policy                                                                                                                                                           
Content-Security-Policy: base-uri 'none'; default-src 'self'; object-src 'none'; script-src 'sha256-NiHKryHWudRC2IteTqmY9v1VkaDUA/5jhgXkMTkgo2w='; frame-ancestors 'self'; block-all-mixed-content; style-src https://cdn.jsdelivr.net 'sha256-y9V0na/WU44EUNI/HDP7kZ7mfEci4PAOIjYOOan6JMA=' 'nonce-J0XZEshlYJMsNi23H63z0w=='
```
After:
```sh-session
$ curl …
```
> Don't generate a nonce

- Gemfile.lock
- maintenance_tasks.gemspec
Releasing this diff https://github.com/Shopify/maintenance_tasks/compare/v2.1.1...260702f72f244e5d77122fb190a707d5d1157946
Main feature is the `parent_controller` controller configuration but support to Ruby 2.7 was also removed.
There are a few bug fixes that I'll list in the releases notes as well.
> Prepare to 2.2.0

- lib/maintenance_tasks/cli.rb
- test/lib/maintenance_tasks/cli_test.rb
Loading all tasks is only necessary when displaying the long description for the `perform` task. Any other operation from the CLI (such as displaying the general help message or performing a task) should not load all tasks.
> Avoid loading all tasks when first loading the CLI

- app/models/maintenance_tasks/task.rb
- app/models/maintenance_tasks/task_data_index.rb
- lib/maintenance_tasks/cli.rb
- test/lib/maintenance_tasks/cli_test.rb
- test/models/maintenance_tasks/task_test.rb
`Task.available_tasks` not only returns all descendants of the `Task` class, it also `require`s all files in the application that may be defining such class.
`available_tasks` does not carry explicit meaning of how heavy the operation could be, so this renames it to `load_all`, which should be better at communicating that, and deprecates the old name.
I'll have to adjust this PR once https://github.com/Shopify/maintenance_tasks/pull/877 is merged.
> Rename `Task.available_tasks` to `.load_all` and deprecate

- lib/maintenance_tasks/cli.rb
- test/lib/maintenance_tasks/cli_test.rb
- test/test_helper.rb
This is an alternative to https://github.com/Shopify/maintenance_tasks/pull/913, which I actually prefer.
A couple months ago, in https://github.com/Shopify/maintenance_tasks/pull/877, I did some weird stuff in order to defer task loading when it's actually necessary. The issue was that we needed the list of all tasks to set the long description of the `perform` command.
I realized that it might actually allow us to keep code more standard and simple, if instead of that, we provided a `list` command that loads and lists all available tasks.
- The CLI still doesn't need to load all tasks at "boot". (the original goal of #877)
- We don't need to use meta-programming to `define_singleton_method :long_description`, which relies on not-so-public APIs, and as shown by the release of Thor 1.3.0, …
> Introduce `list` command in CLI

- app/models/maintenance_tasks/run.rb
- test/models/maintenance_tasks/run_test.rb
Fixes: https://github.com/Shopify/maintenance_tasks/pull/921#discussion_r1420342948
> Fix pause method

- test/application_system_test_case.rb
With Chrome 120, the default headless is now a different binary, causing Selenium to fail to inject its extensions, we can't get logs, etc. See more in https://github.com/SeleniumHQ/selenium/pull/13271
Instead of waiting for a new release of `selenium-webdriver` that includes the fix to continue using the old headless, or configuring Selenium to use an older version of Chrome, this moves to the new headless Chrome.
I had two issues doing that:
1. The preferences to configure the download path does not seem respected by the new headless Chrome, but I found that Selenium had [some code in place to configure the download path](https://github.com/SeleniumHQ/selenium/blob/selenium-4.16.0/rb/lib/selenium/webdriver/common/driver_extensions/downloads_files.rb), so I used that instead. …
> Fix Chrome headless

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- bin/setup
I just noticed there's a warning on the workflow run summary when there's a CI failure but no screenshot to send. Here's a workflow run with the warning annotation: https://github.com/Shopify/maintenance_tasks/actions/runs/3410427916
While testing this, I noticed that if multiple jobs have the same artifact names, we get an error:
https://github.com/Shopify/maintenance_tasks/actions/runs/7260665234
Before we upgraded actions/upload-artifact in #935, that somehow worked by only saving one of the screenshots, see the artifact in https://github.com/Shopify/maintenance_tasks/actions/runs/7260773169.
https://github.com/actions/upload-artifact/tree/cf8714cfeaba5687a442b9bcb85b29e23f468dfa#not-uploading-to-the-same-artifact
I also had one run [taking …
> CI improvements

- app/views/maintenance_tasks/runs/_arguments.html.erb
- app/views/maintenance_tasks/runs/_metadata.html.erb
- app/views/maintenance_tasks/runs/_run.html.erb
- app/views/maintenance_tasks/runs/_serializable.html.erb
- app/views/maintenance_tasks/tasks/_task.html.erb
- test/system/maintenance_tasks/runs_test.rb
As the example in the README, a common use case of metadata is to record who ran the task. By displaying metadata in the web UI, we can know who ran the task at a glance.
> Show Run#metadata in the web UI

- app/validators/maintenance_tasks/run_status_validator.rb
- app/views/maintenance_tasks/runs/_run.html.erb
- test/system/maintenance_tasks/runs_test.rb
- test/validators/maintenance_tasks/run_status_validator_test.rb
Allows clicking "Resume" on an errored run to resume the run from the errored point, preserving progress. This is useful for transient errors, like those from infrastructure, which have not yet been anticipated.
I'm not sure this is quite right, but I wanted to throw up some code to discuss 🙏
Fixes #851.
> Allow resuming errored task runs

- app/views/maintenance_tasks/runs/_run.html.erb
- test/system/maintenance_tasks/tasks_test.rb
It makes correlating runs and errors from an error reporting system easier.
> Show Run#id in the web UI

- README.md
- app/models/maintenance_tasks/run.rb
- lib/maintenance_tasks.rb
- test/jobs/maintenance_tasks/task_job_test.rb
- test/models/maintenance_tasks/run_test.rb
- test/system/maintenance_tasks/runs_test.rb
Having `STUCK_TASK_TIMEOUT` as a constant is not helpful since the actual value will be highly dependent on the job infrastructure of the applications. Simple setups may consider the task being stuck after no updates for ~ 1 minute while more complex and distributed systems with job retries and backoffs may legitimately prefer higher threshold to account for natural delays in a distributed system
It's a breaking change for applications that relied on  `STUCK_TASK_TIMEOUT` though the fix is going to be pretty straightforward. 
Is `MaintenanceTasks` module a right place for the config to live? One common alternative would be to define it on the `Task` class which will allow redefining it on per-task basis. But I don't think this would make sense and the behavior is job-infra specific rather …
> Add `MaintenanceTasks.stuck_task_duration ` configuration

- README.md
- app/jobs/concerns/maintenance_tasks/task_job_concern.rb
- app/models/maintenance_tasks/task.rb
- test/dummy/app/tasks/maintenance/custom_enumerating_task.rb
- test/jobs/maintenance_tasks/task_job_test.rb
- test/models/maintenance_tasks/task_data_index_test.rb
- test/models/maintenance_tasks/task_test.rb
- test/system/maintenance_tasks/tasks_test.rb
This is based on the work in https://github.com/Shopify/maintenance_tasks/pull/326 and the design suggested by @adrianna-chang-shopify in [this comment](https://github.com/Shopify/maintenance_tasks/pull/326#pullrequestreview-613240141).
It allows tasks to define their own custom enumerators, in order to support use cases like iteration over external API resources, or alternative database querying strategies.
It does this by exposing an overridable `enumerator_builder` method on `Task`, whose default implementation is the existing `collection` type inspection logic.
Fixes https://github.com/Shopify/maintenance_tasks/issues/207
> Custom enumerators

- .github/workflows/ci.yml
This will allow us to catch issues with gem upgrades early, hopefully before someone writes a PR and all the jobs fail except the default Gemfile one (with the locked versions).
Due to the way GitHub Actions workflow notifications work, I'll be the one to receive notifications (until someone else edits the `cron` line):
> Notifications for scheduled workflows are sent to the user who initially created the workflow. If a different user updates the cron syntax in the workflow file, subsequent notifications will be sent to that user instead. If a scheduled workflow is disabled and then re-enabled, notifications will be sent to the user who re-enabled the workflow rather than the user who last modified the cron syntax.
> https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflo …
> Run CI on a schedule

- README.md
- app/models/maintenance_tasks/task.rb
- test/jobs/maintenance_tasks/task_job_test.rb
- test/models/maintenance_tasks/task_test.rb
`JobIteration::ActiveRecordCursor#condition` adds an `order by` clause to the relation returned by the `collection` method. It default to order on the `id` column, see `JobIteration::ActiveRecordCursor#initialize`.
Ordering on `id` only can degrade performance significantly depending on which indexes are defined.
`job-iteration` supports configuring which columns are used to order the cursor. This PR explores a way to expose this ability in the `maintenance-tasks` gem.
> Expose ActiveJob ability to customize the columns used to order the cursor

- app/helpers/maintenance_tasks/tasks_helper.rb
- test/dummy/app/tasks/maintenance/params_task.rb
- test/helpers/maintenance_tasks/tasks_helper_test.rb
- test/models/maintenance_tasks/task_data_show_test.rb
- test/system/maintenance_tasks/tasks_test.rb
Super excited about this [dropdown feature](https://github.com/Shopify/maintenance_tasks/pull/925)! -- but I noticed for example `validates_inclusion_of`'s`:in` also supports proc, lambda, or symbol, so would like to ~~extend on this feature~~ fix these types as the views aren't rendering when they are passed.
This allows you to write:
```ruby
attribute :type, :string
validates_inclusion_of :type, in: ->(_record) { ['new', 'old'] }
```
> Fix dropdown options from not rendering views with proc, lamda, symbol inclusion options

- README.md
- app/models/maintenance_tasks/run.rb
- test/jobs/maintenance_tasks/task_job_test.rb
- test/models/maintenance_tasks/run_test.rb
closes https://github.com/Shopify/maintenance_tasks/issues/747
Callbacks on the task are not meant to be used for instrumentation across all tasks. `Task` callbacks also don't have access to the `Run` object, preventing this logic from accessing the metadata or other information stored on the run. This makes it difficult to set notifications for status changes, for instance to send slack messages when a job is completed
Send [active support notifications](https://api.rubyonrails.org/classes/ActiveSupport/Notifications.html) on the Run status changes
```
maintenance_tasks.enqueued,    # The task has been enqueued by the user.
maintenance_tasks.succeeded,   # The task finished without error.
maintenance_tasks.cancelled,   # The user explicitly halted the task's execution. …
```
> send active support notifications on run events

- README.md
There were a couple incorrectly formatted markdown links that weren't rendering and pointing to the subsection they intended.
> Fix incorrect links to subsections of ReadMe.md

- Gemfile
- Gemfile.lock
> Don't use better_html 2.1.0

- .rubocop.yml
Since RuboCop 1.61, the required ruby version from the gemspec takes precedence over the version in .ruby-version.
And since v2.2.0, we don't support Ruby 2.7 so no need to keep our syntax compatible with it.
> Remove outdated TargetRubyVersion in RuboCop config

- README.md
- app/models/maintenance_tasks/csv_collection_builder.rb
> CSV accurate count

- README.md
- app/models/maintenance_tasks/batch_csv_collection_builder.rb
- app/models/maintenance_tasks/csv_collection_builder.rb
- app/models/maintenance_tasks/task.rb
- test/dummy/app/tasks/maintenance/import_posts_with_options_task.rb
- test/models/maintenance_tasks/csv_collection_builder_test.rb
- test/models/maintenance_tasks/csv_task_test.rb
- test/models/maintenance_tasks/task_data_index_test.rb
- test/models/maintenance_tasks/task_test.rb
- test/system/maintenance_tasks/tasks_test.rb
This allows tasks to pass [options for Ruby's CSV parser](https://ruby-doc.org/3.3.0/stdlibs/csv/CSV.html#class-CSV-label-Options+for+Parsing) which can do useful things like automatically coercing numbers and dates, stripping whitespace, etc. While those things could also be implemented in a task itself, other things like skipping over certain non-CSV (comment) lines or defining the separators prevent the parser from raising errors.
> Allow csv_collection to pass options to CSV parser

- Gemfile
- gemfiles/rails_6_0.gemfile
- gemfiles/rails_6_1.gemfile
- gemfiles/rails_7_0.gemfile
Fix #1007 
Dependabot will still try to update sqlite3 in Gemfile.lock and that will still fail, but that will happen whether or not we set a requirement there.
We can then ignore the major entirely, but we'll need to remember to bump sqlite3 once Rails 7.2 ships and is in Gemfile.lock.
> Prevent sqlite3 2.0 except for Rails edge

- bin/production
Fix:
```
$ bin/production
+ export RAILS_ENV=production
+ RAILS_ENV=production
++ bin/rails app:secret
+ SECRET_KEY_BASE='Unrecognized command "app:secret" (Rails::Command::UnrecognizedCommandError)
Did you mean?  app:db:reset'
```
Now:
```
$ bin/production
+ export RAILS_ENV=production
+ RAILS_ENV=production
++ bin/rails secret
+ SECRET_KEY_BASE=aec0d54abaeba02918b23da4e2ebbd08286e0dbc43ef488c03fb819cce8e7301a372b897783855d4fc253690ede1d8ed6756649167d65f41ab07952c15a994be
+ export SECRET_KEY_BASE
+ bin/rails app:assets:precompile
+ DISABLE_DATABASE_ENVIRONMENT_CHECK=true
+ bin/rails db:setup
Created database 'db/production.sqlite3'
+ RAILS_SERVE_STATIC_FILES=true
+ bin/rails server
=> Booting Puma
=> Rails 7.1.3.3 application starting in production
=> Run `bin/rails server --help` for …
```
> Use bin/rails secret in bin/production

- README.md
- app/jobs/concerns/maintenance_tasks/task_job_concern.rb
- app/models/maintenance_tasks/task.rb
- test/dummy/app/tasks/maintenance/import_posts_with_options_task.rb
- test/dummy/app/tasks/maintenance/update_posts_task.rb
- test/jobs/maintenance_tasks/task_job_test.rb
Closes: https://github.com/Shopify/maintenance_tasks/issues/890
This PR adds a task DSL for specifying the batch size on an Active Record Relation collection. Currently, job-iteration will default to fetching 100 records with `active_record_on_records`, which is rather small for a table with many thousands of rows. Task authors can now customize the batch size per task with a `collection_batch_size` method.
> Allow Active Record collection tasks to specify a batch size.

- app/views/maintenance_tasks/tasks/show.html.erb
Rails tries to parse `render` calls in partials to generate a tree of dependencies that should be included in the cache key for a template/partial. The `RenderParser` is also used by gems such as ActionView::Precompiler and LooseErbs for similar purposes (identifying template/partial dependencies).
Currently, `render @task.active_runs` and `render @runs_page.records` cannot be resolved by the `RenderParser` (this is a documented shortcoming of the `RenderParser`).
This commit makes the two partial dependencies explicit as recommended in the `ActionView::CacheHelper` docs. This should not change the behavior of the renders, but it does enable the `RenderParser` to identify the partials being rendered.
> Fix statically resolving renders in Task#show

- README.md
Fixes #1049
`#enumerator_builder` is the right method to test, while `#build_enumerator` is an internal method on a different class.
> Replace build_enumerator with enumerator_builder in README

- lib/generators/maintenance_tasks/install_generator.rb
- test/dummy/config/routes.rb
- test/lib/generators/maintenance_tasks/install_generator_test.rb
Hash syntax was deprecated in https://github.com/rails/rails/pull/52422
This PR addresses deprecation by using `at:` keyword argument instead as the deprecation suggests.
> Do not use hash-based syntax to mount an engine

- test/test_helper.rb
`uri` switched the default parser from RFC2396 to RFC3986. The new parser emits a deprecation warning on a few methods and delegates them to RFC2396. See https://github.com/ruby/uri/pull/114.
The selenium-webdriver gem [calls `URI::RFC3986_PARSER.escape`][webdriver-callsite], which is now deprecated. Until this is fixed in `selenium-webdriver`, ignore the warning.
Fixes failing weekly CI build: https://github.com/Shopify/maintenance_tasks/actions/runs/11769507051/job/32815543032
[webdriver-callsite]: https://github.com/SeleniumHQ/selenium/blob/trunk/rb/lib/selenium/webdriver/remote/bridge.rb#L679
> Ignore URI::RFC3986_PARSER.escape deprecation warning

- README.md
- app/views/maintenance_tasks/runs/_run.html.erb
- config/routes.rb
Fix #992
While we can't automatically get full compatibility with API-only applications, we can make it easier by not using `PUT` and documenting how to add the missing middleware necessary for our engine.
> Better support API-only Rails applications

- Gemfile
- Gemfile.lock
- test/test_helper.rb
Dependabot somehow resolves Rails to 0.9.5 when upgrading job-iteration, and downgrades the Rails frameworks to 7.2.2.1. This makes sure this can't happen.
I also had to silence the JobIteration deprecator so that this is mergeable.
> Require minimum Rails version in Gemfile

- Gemfile.lock
- maintenance_tasks.gemspec
Just to resolve the deprecation in job-iteration.
---
* Wrap enumerators to avoid JobIteration deprecation by @etiennebarrie in https://github.com/Shopify/maintenance_tasks/pull/1140
> Release v2.10.1

- .github/workflows/ci.yml
- maintenance_tasks.gemspec
Proposing we raise the minimum supported Ruby version from 3.1 to 3.2 as the former is EOL. As a bonus, allows us to clean up the CI configuration a little bit.
> Ruby 3.1
>
> status: eol
> release date: 2021-12-25
> normal maintenance until: 2024-04-01
> EOL: 2025-03-26
Source: https://www.ruby-lang.org/en/downloads/branches/
> Raise minimum required Ruby version from 3.1 to 3.2 as the former is EOL

- test/system/maintenance_tasks/tasks_test.rb
If the navigation to the task page hasn't finished, it's not yet time to search for the content field.
Close #1231
> Make system test more resilient

- app/models/maintenance_tasks/run.rb
- test/models/maintenance_tasks/run_test.rb
~This can lead to increased contention on writes to the `maintenance_tasks_runs` table. We mainly care about race conditions for run status updates; incrementing the lock version on every tick count update is unnecessary.~
As @etiennebarrie reminded me in the comments, this PR actually doesn't prevent increment the DB lock version, it just removes the code to keep the in-memory one in sync. This is still worth shipping since there's no real point in updating the in-memory attribute, since we immediately call `reload_status` after to refresh the lock version from the DB. We may want to re-evaluate relying on `#update_counters`.
> Avoid incrementing in-memory lock version on tick count updates

- Gemfile.lock
Simple maintenance PR to upgrade `bundler` version to latest to pick up a bunch of fixes and improvements.
- https://github.com/rubygems/rubygems/releases/tag/bundler-v2.6.4
- https://github.com/rubygems/rubygems/releases/tag/bundler-v2.6.5
- https://github.com/rubygems/rubygems/releases/tag/bundler-v2.6.6
- https://github.com/rubygems/rubygems/releases/tag/bundler-v2.6.7
- https://github.com/rubygems/rubygems/releases/tag/bundler-v2.6.8
- https://github.com/rubygems/rubygems/releases/tag/bundler-v2.6.9
Note, I do kind of expect a v2.6.10 or v2.7.0 to be released at some point soon re: v2.6.9 being released in May but at the same time, could be a while so, might as well get up to date. :man_shrugging:
> Upgrade bundler from 2.6.3 to 2.6.9

- README.md
- app/jobs/concerns/maintenance_tasks/task_job_concern.rb
- app/models/maintenance_tasks/task.rb
- lib/maintenance_tasks.rb
- test/jobs/maintenance_tasks/task_job_test.rb
- test/models/maintenance_tasks/task_test.rb
In our monolith, we're noticing frequent calls to the DB to reload the status, especially on tasks that iterate very quickly. This should help reduce that load by allowing tasks to specify how often the run status should be reloaded during iteration. A global default can be configured, and the value can also be configured on a per-task basis.
Note that decreasing the reload frequency impacts how quickly your task will stop if it is paused or interrupted. This config will be primarily useful for tasks that don't need to check for cancellation/pausing very often.
I've opted to configure reloads based on time-based frequency rather than iteration-based frequency. This aligns more closely with how ticker persistence works and makes more sense than using the number of iterations, since …
> Add configurable status reload frequency

- .github/workflows/ci.yml
- .github/workflows/stale.yml
Locks the three GitHub Actions dependencies to specific versions via said versions' SHAs.
1. Locking to SHAs is best practice for security and sanity as we know which version is being used. Without doing Actions will simply use whatever latest version is available, a silent bump of sorts. For example, actions/checkout just released a [v4.3.0](https://github.com/actions/checkout/releases/tag/v4.3.0) today, which will be used automatically.
~2. With locking to SHAs we should receive (albeit somewhat rare) Dependabot upgrade PRs for said Actions dependencies which version is in use will be explicit and thus can be updated explicitly. For example, [actions/checkout v5.0.0](https://github.com/actions/checkout/releases/tag/v5.0.0) was just released today. After this PR I expect we'll receive a …
> Lock GitHub Actions dependencies to SHAs for security and predictability
