Shopify/maintenance_tasks

README.md
Our README has gotten pretty long. A Table of Contents should hopefully help with navigation / information discoverability.
PR also cleans up the README a little bit.
=> Add a Table of Contents to the README

Gemfile.lock, maintenance_tasks.gemspec
Closes: https://github.com/Shopify/maintenance_tasks/issues/285
Let's get this baby out into the world! 🎉
=> Bump to 1.0

app/tasks/maintenance_tasks/task.rb, test/tasks/maintenance_tasks/task_test.rb
=> Restrict Task.named to only return Task classes

Gemfile.lock, maintenance_tasks.gemspec
Let's ship this patch version will all our 🐞  fixes.
I've updated the release notes, but let's make sure we haven't missed anything.
=> Release v1.1.1

Gemfile.lock, maintenance_tasks.gemspec
Includes this fix: https://github.com/Shopify/maintenance_tasks/pull/359
=> Bump to 1.1.2

Gemfile.lock, maintenance_tasks.gemspec
Cut a new version with ActiveStorage fix (#385)
=> Release v1.2.1

lib/maintenance_tasks.rb
=> Document MaintenanceTasks attributes for YARD

Gemfile.lock, gemfiles/rails_6_0.gemfile.lock, gemfiles/rails_edge.gemfile.lock, maintenance_tasks.gemspec
Let's get throttling shipped, and the couple of fixes we've shipped since 1.2.2 😄 
https://github.com/Shopify/maintenance_tasks/releases/edit/untagged-4599b4815f520c3fb6c4
=> Release 1.3.0

maintenance_tasks.gemspec
Rails encourages the use of binstubs when invoking rails.
=> Added bin prefix to rails command in post-install message  + Use heredoc in post command

app/helpers/maintenance_tasks/tasks_helper.rb, app/models/maintenance_tasks/run.rb, app/views/maintenance_tasks/runs/info/_paused.html.erb, app/views/maintenance_tasks/runs/info/_running.html.erb, test/helpers/maintenance_tasks/tasks_helper_test.rb, test/models/maintenance_tasks/run_test.rb
=> Return a Duration instead of a Time for the ETA

Gemfile.lock, maintenance_tasks.gemspec
Release batch support + custom parameters!
Release: https://github.com/Shopify/maintenance_tasks/releases/edit/untagged-0f4a3a9e79dd98fa8423
=> Release 1.4.0

.github/workflows/ci.yml, Gemfile, Gemfile.lock, test/lib/generators/maintenance_tasks/install_generator_test.rb, test/models/maintenance_tasks/run_test.rb
This is the first step to tackle https://github.com/Shopify/maintenance_tasks/issues/462.
=> Run tests against sqlite and postgres

app/models/maintenance_tasks/progress.rb, test/models/maintenance_tasks/progress_test.rb
Had trouble reading the tick counts otherwise.
Also I created this in the GitHub editor and it was pretty slick but I also have no idea if it's right, so working on that.
=> Delimit ticks in progress text

Gemfile
=> Simple rails requirement that Dependabot can update

.yardopts
Same as the fix in https://github.com/Shopify/job-iteration/pull/160
https://github.com/Shopify/maintenance_tasks/pull/540#issuecomment-984006384
=> Fix broken .yardopts

Gemfile.lock, maintenance_tasks.gemspec
=> Prepare release 1.8.0

app/views/maintenance_tasks/runs/_arguments.html.erb
Fixes https://github.com/Shopify/maintenance_tasks/issues/589 =)
=> Minor fix to the arguments UI

app/models/maintenance_tasks/runner.rb, test/models/maintenance_tasks/runner_test.rb
=> Drop support for MaintenanceTasks::Runner.new

app/models/maintenance_tasks/batch_csv_collection_builder.rb, test/models/maintenance_tasks/batch_csv_collection_builder_test.rb
Co-authored-by: Paulo Barros <paulo.barros@shopify.com>
Fix #615
=> Fix Batch CSV count off by one

app/models/maintenance_tasks/runs_page.rb
Closes: https://github.com/Shopify/maintenance_tasks/issues/676
Instead of querying the database to determine if the stored cursor matches the id of the last `Run` record when calling `RunsPage#last`, we can just load an extra record for every page. This allows us to refactor `RunsPage#last` to simply check for the presence of this extra record, rather than querying the db again.
Prior to these changes, the following queries were produced:
```
MaintenanceTasks::Run Load (0.2ms)  SELECT "maintenance_tasks_runs".* FROM "maintenance_tasks_runs"
WHERE "maintenance_tasks_runs"."task_name" = ? AND "maintenance_tasks_runs"."status" IN (?, ?, ?) AND (id < '4') 
ORDER BY "maintenance_tasks_runs"."created_at" DESC LIMIT ?  
[["task_name", "Maintenance::UpdatePostsTask"], ["status", "succeeded"], …
```
=> Reduce queries required for Runs pagination

Gemfile.lock, maintenance_tasks.gemspec
Draft is here: https://github.com/Shopify/maintenance_tasks/releases/edit/untagged-e79c1a3f1d09cc765fac
I only kept the changes that affect the generated gem, so not the Gemfile.lock changes etc.
=> Release 2.1.0

README.md
Fixing typo I introduced in #819
=> Fix parent_controller example

Gemfile.lock, maintenance_tasks.gemspec
Release new version.
Includes changes to avoid loading extra tasks in the CLI, deprecation of `.available_tasks` in favour of `load_all`, and loosening of job-iteration requirement.
=> Update to v2.3.2

Gemfile, Gemfile.lock
=> Remove unnecessary direct dependencies

Gemfile.lock, maintenance_tasks.gemspec
=> Release 2.3.3

Gemfile.lock, maintenance_tasks.gemspec
Release a minor update including the ActiveSupport notifications for tasks status changes.
=> Bump to 2.7

README.md
Came across a rendering issue when reading the README. It seems like a codeblock wasn't closed properly.
=> Fix formatting error in README.md

app/models/maintenance_tasks/run.rb, lib/patches/active_record_batch_enumerator.rb, test/test_helper.rb
This is all cruft we don't need anymore.
=> Remove code to support old versions

app/views/maintenance_tasks/runs/_run.html.erb
The changes from #1178 were removed by #1163, this brings them back.
=> Restore link to task run on the Run id

app/models/maintenance_tasks/run.rb
In our monolith, we've been hammering the DB with status reload queries due to retries on stale object errors. This PR adds exponential backoff to the stale object error handling. If two processes are updating the same run and both hitting stale object errors, the backoff with jitter should allow one of them to succeed before the other.
Delay ranges for each attempt:
- Attempt 1: 0.1 * 2^0 = 0.1s → 0.075s - 0.125s
- Attempt 2: 0.1 * 2^1 = 0.2s → 0.15s - 0.25s
- Attempt 3: 0.1 * 2^2 = 0.4s → 0.3s - 0.5s
- Attempt 4: 0.1 * 2^3 = 0.8s → 0.6s - 1.0s
- Attempt 5: 0.1 * 2^4 = 1.6s → 1.2s - 2.0s
Existing tests around `StaleObjectError`s continue to pass. I tried to write a test that demonstrated two competing units of work both hitting stale object errors, something like this:
```ruby
test "run …
```
=> Exponential backoff for stale object errors with bounded retries
